### ISSUE TITLE
Chyby u registrace uživatele

### ISSUE THREAD

**Issue by Lukadoss** [Lukadoss/History-web#26]
- Lze se registrovat i přes blokující javascript
- Lze kliknout na submit několikrát -> redirect na jinou stránku, kde se počká na zpracování
- registrace úspěšná
- registrace neúspěšná
- JS zobrazuje anglicky u hesla - Not long enough
- Dá se zabugovat heslo jen na 1-x znaků i přestože je tam blokace na 4 a více znaků

**Comment by Lukadoss** [comment]
Pro nejlepší řešení problémů bych asi použil přímo cakePHP formulář. Dá se s tím lépe zacházet v cake + verifikace, jen nevim jak to je se zobrazením (nebude to asi zas tak hezký jako bootstrap :smiley_cat: ) - 
http://book.cakephp.org/3.0/en/views/helpers/form.html
http://book.cakephp.org/3.0/en/tutorials-and-examples/blog-auth-example/auth.html#creating-all-user-related-code

**Comment by honzaseda** [comment]
přesunuto do issue #32
