### ISSUE TITLE
Zapomenuté heslo

### ISSUE THREAD

**Issue by Lukadoss** [Lukadoss/History-web#30]
- zpracovat zapomenuté heslo - odeslat na mail nové heslo, nebo odkaz na reset hesla nebo nevim... tak nějak
- @honzaseda třeba udělat jednoduchý view

**Comment by honzaseda** [comment]
Template pro obnovení hesla přidán

**Comment by Lukadoss** [comment]
@honzaseda Potřeba udělat ještě template pro reset hesla -> reset.ctp
