### ISSUE TITLE
Chyby při editaci

### ISSUE THREAD

**Issue by Lukadoss** [Lukadoss/History-web#48]
Při editaci znovu schválit příspěvek adminem @Lukadoss
Zobrazování Areatextu - při editaci OK ale při normálním zobrazení neni text odřádkován, je v kuse za sebou.
Možnost posunout marker na mapě @honzaseda 
Možnost mazat/nahrávat soubory @hard456

**Comment by honzaseda** [comment]
posouvání markeru hotovo

**Comment by Lukadoss** [comment]
Znovuschválení hotovo, +admin při editaci nemusí schvalovat

**Comment by ghost** [comment]
Chyby při editaci umim dělat, můžu pomoct, klucí. :+1:
